# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install Poetry into the Read the Docs virtual environment
      - pip install poetry
      # Tell Poetry to not create its own virtualenv, as RTD already provides one
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs
